### ISSUE TITLE
Can you provide your pytorch, cuda and gpu version?

### ISSUE THREAD

**Issue by Meow-2** [xuhangc/shadow#3]
I ran into this problem when running `python train_removal.py`

```
/opt/conda/conda-bld/pytorch_1676880686002/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [169,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
  0%|                                                                                                                       | 0/67 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/zk/Code/Python/ShadocNet/train_removal.py", line 142, in <module>
    main()
  File "/home/zk/Code/Python/ShadocNet/train_removal.py", line 109, in main
    out, loss = remove(inp, gt_mas, mas, foremas, tar)
  File "/home/zk/.conda/envs/dl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zk/Code/Python/ShadocNet/model/removal/ss_curve.py", line 107, in forward
    f_features, b_features = self.encode_forward(inp, mas, foremas)
  File "/home/zk/Code/Python/ShadocNet/model/removal/ss_curve.py", line 89, in encode_forward
    fg_encode = self.multimae.forward(
  File "/home/zk/Code/Python/ShadocNet/model/removal/mae.py", line 394, in forward
    input_tokens = torch.gather(input_tokens, dim=1,
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Have you ever encountered this problem？Is this a code error？
Or it‘s a bug related to pytorch version.facebookresearch/detectron2#2837

**Comment by Meow-2** [comment]
Refer to https://github.com/pytorch/pytorch/issues/55027#issuecomment-1047300602, it may not be pytorch’s problem. And I downgrade my torch from 2.0 to 1.13, the error still happened.

Maybe I'm running the code the wrong way.
This is the way I run the code:
1. adjust the dataset path in config/config.py
2. make yml config
3. run `python train_detect.py`, it runs well
4. run `python test_detect.py`, it runs well
5. run `python train_removal.py`, the error happened

Please tell me how to run it correctly.

**Comment by Meow-2** [comment]
> Refer to [pytorch/pytorch#55027 (comment)](https://github.com/pytorch/pytorch/issues/55027#issuecomment-1047300602), it may not be pytorch’s problem. Maybe I'm running the code the wrong way. After adjust the dataset path, I run `python train_detect.py`, it runs well, then I run `python train_removal.py`, the error happened.

Please tell me how to run it correctly.

**Comment by xuhangc** [comment]
Hi, this is not a PyTorch or CUDA issue. I encountered a similar problem in the past, where the shadow detection module failed to detect the shadow mask, resulting in errors due to the tokens being related to the shadow region. To address this, you could try fine-tuning the existing shadow detector, adjusting its parameters, or building a new one. Once the shadow detection module is functioning properly, the issue should be resolved.

**Comment by Meow-2** [comment]
> Hi, this is not a PyTorch or CUDA issue. I encountered a similar problem in the past, where the shadow detection module failed to detect the shadow mask, resulting in errors due to the tokens being related to the shadow region. To address this, you could try fine-tuning the existing shadow detector, adjusting its parameters, or building a new one. Once the shadow detection module is functioning properly, the issue should be resolved.

Thanks for your reply.I had retrained several detector on Jung or Kligler, but still get that error. Can provide me with a pre-training detector?

**Comment by xuhangc** [comment]
> > Hi, this is not a PyTorch or CUDA issue. I encountered a similar problem in the past, where the shadow detection module failed to detect the shadow mask, resulting in errors due to the tokens being related to the shadow region. To address this, you could try fine-tuning the existing shadow detector, adjusting its parameters, or building a new one. Once the shadow detection module is functioning properly, the issue should be resolved.
> 
> Thanks for your reply.I had retrained several detector on Jung or Kligler, but still get that error. Can provide me with a pre-training detector?

Sure, I will notify you once I upload the weights.

**Comment by xuhangc** [comment]
> Refer to [pytorch/pytorch#55027 (comment)](https://github.com/pytorch/pytorch/issues/55027#issuecomment-1047300602), it may not be pytorch’s problem. And I downgrade my torch from 2.0 to 1.13, the error still happened.
> 
> Maybe I'm running the code the wrong way. This is the way I run the code:
> 
> 1. adjust the dataset path in config/config.py
> 2. make yml config
> 3. run `python train_detect.py`, it runs well
> 4. run `python test_detect.py`, it runs well
> 5. run `python train_removal.py`, the error happened
> 
> Please tell me how to run it correctly.

Hi, I have refactored the code and it is now functional for single GPU training. I have tested it on my personal machine and have confirmed its efficacy. However, there still seems to be an issue with multi-GPU training. I will inform you as soon as the issue is resolved.

**Comment by xuhangc** [comment]
Also, if you find it difficult to train the detection module, we recommend trying our [shadow generation technique](https://github.com/CXH-Research/Shadow-Generation) to produce pseudo-shadow document images for training. This technique can greatly improve performance.
